server:
  port: 8081
feign:
  okhttp:
    enabled: true

#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher


  datasource:
    url: jdbc:mysql://localhost:3308/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#처음엔 여러 데이터 테스트 용으로 create 했지만 이는 위험하니
#update
