server:
  shutdown: graceful
  port: 8082

feign:
  okhttp:
    enabled: true

#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher


  datasource:
    url: jdbc:mysql://localhost:3308/zeroorder
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379
